### ISSUE TITLE
Cannot check premium state from authlib-injector

### ISSUE THREAD

**Issue by awang-karisma** [elyby/accounts#13]
Hello, I am sorry if this is not the right place to ask, but I figured that this can only be fixed from ely.by side.

I recently tried authlib-injector to use ely.by as authentication method. Everything works perfectly until some plugins trying to check user premium state by querying /api/users/profiles/minecraft/<user name>

I tried to open the api endpoint from browser ( authserver.ely.by/api/users/profiles/minecraft/<user name> ), it works as intended. But when i try it with authlib-injector in the server, the plugin that checks premium state throws error, because authlib-injector has different endpoint from what i see in the log ( authserver.ely.by/api/authlib-injector/api/users/profiles/minecraft/<user name> )

here's the error log
```
[01:19:24 INFO]: [FastLogin] Handling player <user name>
[01:19:24 ERROR]: [FastLogin] Failed to check premium state for <user name>
java.io.FileNotFoundException: https://authserver.ely.by/api/authlib-injector/api/users/profiles/minecraft/<user name>
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1974) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1969) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:738) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1968) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1536) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250) ~[?:?]
        at com.github.games647.craftapi.resolver.MojangResolver.findProfile(MojangResolver.java:179) ~[?:?]
        at com.github.games647.fastlogin.core.shared.JoinManagement.onLogin(JoinManagement.java:55) ~[?:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.NameCheckTask.run(NameCheckTask.java:45) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:836) [?:?]
Caused by: java.io.FileNotFoundException: https://authserver.ely.by/api/authlib-injector/api/users/profiles/minecraft/<user name>
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1920) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520) ~[?:?]
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334) ~[?:?]
        at com.github.games647.craftapi.resolver.MojangResolver.findProfile(MojangResolver.java:164) ~[?:?]
        ... 6 more
[01:19:24 ERROR]: [FastLogin] Failed to check premium state of <user name>
java.io.FileNotFoundException: https://authserver.ely.by/api/authlib-injector/api/users/profiles/minecraft/<user name>
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1974) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1969) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:738) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1968) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1536) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250) ~[?:?]
        at com.github.games647.craftapi.resolver.MojangResolver.findProfile(MojangResolver.java:179) ~[?:?]
        at com.github.games647.fastlogin.core.shared.JoinManagement.onLogin(JoinManagement.java:55) ~[?:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.NameCheckTask.run(NameCheckTask.java:45) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:836) [?:?]
Caused by: java.io.FileNotFoundException: https://authserver.ely.by/api/authlib-injector/api/users/profiles/minecraft/<user name>
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1920) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520) ~[?:?]
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334) ~[?:?]
        at com.github.games647.craftapi.resolver.MojangResolver.findProfile(MojangResolver.java:164) ~[?:?]
        ... 6 more
```
Possible fix : points `https://authserver.ely.by/api/authlib-injector/api/` to `https://authserver.ely.by/api/`

Thank you !

**Comment by erickskrauch** [comment]
This is quite strange behavior. We don't specify anywhere to use the authlib-injector via the `authserver.ely.by` domain. Redirects that are written for the main domain `ely.by` lead to the subdomain `account.ely.by`. Please try to specify just `ely.by` as the address for the authlib-injector. [Docs](https://docs.ely.by/en/authlib-injector.html#server).

**Comment by awang-karisma** [comment]
Seems like i mixed and matched tutorial found on [this page](https://docs.ely.by/ru/api.html) 
Also i tried to reproduce the error, but it didn't show up anymore, both using javaagent and jar patching method.

Will close for now and will inform if this occur later

Thanks!
